version: '3'

services:
  fast-api:
    container_name: fast_api
    build: .
    volumes:
      - .:/app/backend

    command: ['uvicorn', 'core.main:app', '--reload', '--host', '0.0.0.0', '--port','8000']
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file: .env
 
  mongo:
    container_name: mongo_db
    image: mongo
    volumes:
      - ./data-mongodb:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine

networks:
  default:
    external:
      name: micro-service