version: '3'

services:
  backend:
    container_name: fast_api
    build: .
    volumes:
      - .:/app/backend

    command: ['uvicorn', 'user.core.main:app', '--reload', '--host', '0.0.0.0', '--port','8000']
    ports:
      - "8000:8000"
    depends_on:
      - mongo
 
  mongo:
    container_name: mongo_db
    image: mongo
    volumes:
      - ./data-mongodb:/data/db
    ports:
      - "27017:27017"
